USE [master]
GO
/****** Object:  Database [HMO_PROGECT]    Script Date: 30/10/2019 20:53:02 ******/
CREATE DATABASE [HMO_PROGECT] ON  PRIMARY 
( NAME = N'HMO_PROGECT', FILENAME = N'D:\SQL-DATA\HMO_PROGECT.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'HMO_PROGECT_log', FILENAME = N'D:\SQL-DATA\HMO_PROGECT_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [HMO_PROGECT] SET COMPATIBILITY_LEVEL = 100
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [HMO_PROGECT].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [HMO_PROGECT] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [HMO_PROGECT] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [HMO_PROGECT] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [HMO_PROGECT] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [HMO_PROGECT] SET ARITHABORT OFF 
GO
ALTER DATABASE [HMO_PROGECT] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [HMO_PROGECT] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [HMO_PROGECT] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [HMO_PROGECT] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [HMO_PROGECT] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [HMO_PROGECT] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [HMO_PROGECT] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [HMO_PROGECT] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [HMO_PROGECT] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [HMO_PROGECT] SET  DISABLE_BROKER 
GO
ALTER DATABASE [HMO_PROGECT] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [HMO_PROGECT] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [HMO_PROGECT] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [HMO_PROGECT] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [HMO_PROGECT] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [HMO_PROGECT] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [HMO_PROGECT] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [HMO_PROGECT] SET RECOVERY FULL 
GO
ALTER DATABASE [HMO_PROGECT] SET  MULTI_USER 
GO
ALTER DATABASE [HMO_PROGECT] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [HMO_PROGECT] SET DB_CHAINING OFF 
GO
EXEC sys.sp_db_vardecimal_storage_format N'HMO_PROGECT', N'ON'
GO
USE [HMO_PROGECT]
GO
/****** Object:  User [students\hitmachut]    Script Date: 30/10/2019 20:53:03 ******/
CREATE USER [students\hitmachut] FOR LOGIN [STUDENTS\hitmachut] WITH DEFAULT_SCHEMA=[dbo]
GO
ALTER ROLE [db_owner] ADD MEMBER [students\hitmachut]
GO
ALTER ROLE [db_accessadmin] ADD MEMBER [students\hitmachut]
GO
ALTER ROLE [db_securityadmin] ADD MEMBER [students\hitmachut]
GO
ALTER ROLE [db_ddladmin] ADD MEMBER [students\hitmachut]
GO
ALTER ROLE [db_backupoperator] ADD MEMBER [students\hitmachut]
GO
ALTER ROLE [db_datareader] ADD MEMBER [students\hitmachut]
GO
ALTER ROLE [db_datawriter] ADD MEMBER [students\hitmachut]
GO
ALTER ROLE [db_denydatareader] ADD MEMBER [students\hitmachut]
GO
ALTER ROLE [db_denydatawriter] ADD MEMBER [students\hitmachut]
GO
/****** Object:  Table [dbo].[AGE_TBL]    Script Date: 30/10/2019 20:53:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AGE_TBL](
	[ageId] [int] IDENTITY(1,1) NOT NULL,
	[begins] [int] NULL,
	[ends] [int] NULL,
 CONSTRAINT [PK_AGE_TBL] PRIMARY KEY CLUSTERED 
(
	[ageId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CATEGORIES_TBL]    Script Date: 30/10/2019 20:53:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CATEGORIES_TBL](
	[categoriesId] [int] IDENTITY(1,1) NOT NULL,
	[categoryName] [nvarchar](50) NULL,
	[parentCategory] [int] NULL,
	[createBy] [nvarchar](50) NULL,
	[status] [bit] NULL,
 CONSTRAINT [PK_CATEGORIES_TBL] PRIMARY KEY CLUSTERED 
(
	[categoriesId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[HMO_TBL]    Script Date: 30/10/2019 20:53:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HMO_TBL](
	[hmoId] [int] NOT NULL,
	[hmoName] [nvarchar](50) NULL,
	[hmoMail] [nvarchar](50) NULL,
 CONSTRAINT [PK_HMO_TBL] PRIMARY KEY CLUSTERED 
(
	[hmoId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[INSURANCE_TBL]    Script Date: 30/10/2019 20:53:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[INSURANCE_TBL](
	[insuranceId] [int] IDENTITY(5,5) NOT NULL,
	[hmoId] [int] NOT NULL,
	[insuranceName] [nvarchar](50) NULL,
	[InsurancePrice] [float] NULL,
	[description] [char](70) NULL,
 CONSTRAINT [PK_INSURANCE_TBL] PRIMARY KEY CLUSTERED 
(
	[insuranceId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRICE]    Script Date: 30/10/2019 20:53:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRICE](
	[priceId] [int] IDENTITY(1,1) NOT NULL,
	[priceText] [float] NULL,
	[productId] [int] NOT NULL,
	[insuranceId] [int] NOT NULL,
	[ageId] [int] NULL,
	[discount] [float] NULL,
 CONSTRAINT [PK_PRICE] PRIMARY KEY CLUSTERED 
(
	[priceId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRODUCTS_TBL]    Script Date: 30/10/2019 20:53:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRODUCTS_TBL](
	[productId] [int] IDENTITY(1,1) NOT NULL,
	[description] [nvarchar](200) NOT NULL,
	[categoryId] [int] NOT NULL,
	[imag] [nvarchar](50) NULL,
	[name] [nvarchar](30) NULL,
 CONSTRAINT [PK_PRODUCTS_TBL] PRIMARY KEY CLUSTERED 
(
	[productId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[REQUEST_TBL]    Script Date: 30/10/2019 20:53:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[REQUEST_TBL](
	[categoryName] [nvarchar](50) NOT NULL,
	[parentCategory] [bit] NOT NULL,
	[requestStatus] [int] NULL,
	[requestKind] [int] NOT NULL,
	[categoryId] [int] NOT NULL,
	[requestId] [int] IDENTITY(1,1) NOT NULL,
	[userId] [int] NOT NULL,
 CONSTRAINT [PK_REQUEST_TBL] PRIMARY KEY CLUSTERED 
(
	[requestId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SATISFICATION_TBL]    Script Date: 30/10/2019 20:53:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SATISFICATION_TBL](
	[satisficationId] [int] IDENTITY(1,1) NOT NULL,
	[hmoId] [int] NOT NULL,
	[satisficationOfWebsite] [float] NULL,
	[satisficationOfHmo] [float] NULL,
	[userId] [int] NULL,
	[comment] [nvarchar](300) NULL,
	[date] [datetime] NULL,
 CONSTRAINT [PK_SATISFICATION_TBL] PRIMARY KEY CLUSTERED 
(
	[satisficationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[USERS_TBL]    Script Date: 30/10/2019 20:53:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USERS_TBL](
	[userId] [int] IDENTITY(1,1) NOT NULL,
	[userName] [nvarchar](30) NULL,
	[tz] [nvarchar](9) NOT NULL,
	[password] [nvarchar](5) NULL,
	[hmoId] [int] NULL,
	[isAdmin] [bit] NOT NULL,
	[adress] [nvarchar](50) NULL,
	[mail] [nvarchar](50) NOT NULL,
	[telephone] [nvarchar](13) NULL,
	[requestForm] [nvarchar](500) NULL,
	[isConfirm] [bit] NULL,
	[firstName] [nvarchar](50) NULL,
	[lastName] [nvarchar](100) NULL,
	[isActive] [bit] NULL,
 CONSTRAINT [PK_TBL_USERS] PRIMARY KEY CLUSTERED 
(
	[userId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CATEGORIES_TBL]  WITH CHECK ADD  CONSTRAINT [FK_CATEGORIES_TBL_CATEGORIES_TBL] FOREIGN KEY([categoriesId])
REFERENCES [dbo].[CATEGORIES_TBL] ([categoriesId])
GO
ALTER TABLE [dbo].[CATEGORIES_TBL] CHECK CONSTRAINT [FK_CATEGORIES_TBL_CATEGORIES_TBL]
GO
ALTER TABLE [dbo].[INSURANCE_TBL]  WITH CHECK ADD  CONSTRAINT [FK_INSURANCE_TBL_HMO_TBL] FOREIGN KEY([hmoId])
REFERENCES [dbo].[HMO_TBL] ([hmoId])
GO
ALTER TABLE [dbo].[INSURANCE_TBL] CHECK CONSTRAINT [FK_INSURANCE_TBL_HMO_TBL]
GO
ALTER TABLE [dbo].[PRICE]  WITH CHECK ADD  CONSTRAINT [FK_PRICE_AGE_TBL] FOREIGN KEY([ageId])
REFERENCES [dbo].[AGE_TBL] ([ageId])
GO
ALTER TABLE [dbo].[PRICE] CHECK CONSTRAINT [FK_PRICE_AGE_TBL]
GO
ALTER TABLE [dbo].[PRICE]  WITH CHECK ADD  CONSTRAINT [FK_PRICE_INSURANCE_TBL] FOREIGN KEY([insuranceId])
REFERENCES [dbo].[INSURANCE_TBL] ([insuranceId])
GO
ALTER TABLE [dbo].[PRICE] CHECK CONSTRAINT [FK_PRICE_INSURANCE_TBL]
GO
ALTER TABLE [dbo].[PRICE]  WITH CHECK ADD  CONSTRAINT [FK_PRICE_PRODUCTS_TBL] FOREIGN KEY([productId])
REFERENCES [dbo].[PRODUCTS_TBL] ([productId])
GO
ALTER TABLE [dbo].[PRICE] CHECK CONSTRAINT [FK_PRICE_PRODUCTS_TBL]
GO
ALTER TABLE [dbo].[PRODUCTS_TBL]  WITH CHECK ADD  CONSTRAINT [FK_PRODUCTS_TBL_CATEGORIES_TBL] FOREIGN KEY([categoryId])
REFERENCES [dbo].[CATEGORIES_TBL] ([categoriesId])
GO
ALTER TABLE [dbo].[PRODUCTS_TBL] CHECK CONSTRAINT [FK_PRODUCTS_TBL_CATEGORIES_TBL]
GO
ALTER TABLE [dbo].[REQUEST_TBL]  WITH CHECK ADD  CONSTRAINT [FK_REQUEST_TBL_CATEGORIES_TBL] FOREIGN KEY([categoryId])
REFERENCES [dbo].[CATEGORIES_TBL] ([categoriesId])
GO
ALTER TABLE [dbo].[REQUEST_TBL] CHECK CONSTRAINT [FK_REQUEST_TBL_CATEGORIES_TBL]
GO
ALTER TABLE [dbo].[REQUEST_TBL]  WITH CHECK ADD  CONSTRAINT [FK_REQUEST_TBL_USERS_TBL] FOREIGN KEY([userId])
REFERENCES [dbo].[USERS_TBL] ([userId])
GO
ALTER TABLE [dbo].[REQUEST_TBL] CHECK CONSTRAINT [FK_REQUEST_TBL_USERS_TBL]
GO
ALTER TABLE [dbo].[SATISFICATION_TBL]  WITH CHECK ADD  CONSTRAINT [FK_SATISFICATION_TBL_HMO_TBL] FOREIGN KEY([hmoId])
REFERENCES [dbo].[HMO_TBL] ([hmoId])
GO
ALTER TABLE [dbo].[SATISFICATION_TBL] CHECK CONSTRAINT [FK_SATISFICATION_TBL_HMO_TBL]
GO
ALTER TABLE [dbo].[USERS_TBL]  WITH CHECK ADD  CONSTRAINT [FK_USERS_TBL_HMO_TBL] FOREIGN KEY([hmoId])
REFERENCES [dbo].[HMO_TBL] ([hmoId])
GO
ALTER TABLE [dbo].[USERS_TBL] CHECK CONSTRAINT [FK_USERS_TBL_HMO_TBL]
GO
USE [master]
GO
ALTER DATABASE [HMO_PROGECT] SET  READ_WRITE 
GO
