//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATEGORIES_TBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CATEGORIES_TBL()
        {
            this.PRODUCTS_TBL = new HashSet<PRODUCTS_TBL>();
            this.REQUEST_TBL = new HashSet<REQUEST_TBL>();
        }
    
        public int categoriesId { get; set; }
        public string categoryName { get; set; }
        public Nullable<int> parentCategory { get; set; }
        public string createBy { get; set; }
        public Nullable<bool> status { get; set; }
    
        public virtual CATEGORIES_TBL CATEGORIES_TBL1 { get; set; }
        public virtual CATEGORIES_TBL CATEGORIES_TBL2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCTS_TBL> PRODUCTS_TBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REQUEST_TBL> REQUEST_TBL { get; set; }
    }
}
