//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSURANCE_TBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INSURANCE_TBL()
        {
            this.PRICEs = new HashSet<PRICE>();
        }
    
        public int insuranceId { get; set; }
        public int hmoId { get; set; }
        public string insuranceName { get; set; }
        public Nullable<double> InsurancePrice { get; set; }
        public string description { get; set; }
    
        public virtual HMO_TBL HMO_TBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRICE> PRICEs { get; set; }
    }
}
