//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class REQUEST_TBL
    {
        public string categoryName { get; set; }
        public bool parentCategory { get; set; }
        public Nullable<int> requestStatus { get; set; }
        public int requestKind { get; set; }
        public int categoryId { get; set; }
        public int requestId { get; set; }
        public int userId { get; set; }
    
        public virtual CATEGORIES_TBL CATEGORIES_TBL { get; set; }
        public virtual USERS_TBL USERS_TBL { get; set; }
    }
}
