//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERS_TBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USERS_TBL()
        {
            this.REQUEST_TBL = new HashSet<REQUEST_TBL>();
        }
    
        public int userId { get; set; }
        public string userName { get; set; }
        public string tz { get; set; }
        public string password { get; set; }
        public int hmoId { get; set; }
        public bool isAdmin { get; set; }
        public string adress { get; set; }
        public string mail { get; set; }
        public string telephone { get; set; }
        public string requestForm { get; set; }
        public Nullable<bool> isConfirm { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public Nullable<bool> isActive { get; set; }
    
        public virtual HMO_TBL HMO_TBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REQUEST_TBL> REQUEST_TBL { get; set; }
    }
}
