//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRICE
    {
        public int priceId { get; set; }
        public Nullable<double> priceText { get; set; }
        public int productId { get; set; }
        public int insuranceId { get; set; }
        public Nullable<int> ageId { get; set; }
        public Nullable<double> discount { get; set; }
    
        public virtual AGE_TBL AGE_TBL { get; set; }
        public virtual INSURANCE_TBL INSURANCE_TBL { get; set; }
        public virtual PRODUCTS_TBL PRODUCTS_TBL { get; set; }
    }
}
