//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SATISFICATION_TBL
    {
        public int satisficationId { get; set; }
        public int hmoId { get; set; }
        public Nullable<double> satisficationOfWebsite { get; set; }
        public Nullable<double> satisficationOfHmo { get; set; }
        public Nullable<int> userId { get; set; }
        public string comment { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual HMO_TBL HMO_TBL { get; set; }
    }
}
